image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - yarn

test:
  stage: test
  script:
    - CI=true yarn test --passWithNoTests

pages:
  stage: deploy
  script:
    - CI=true yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
